/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/objects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Список объектов строительства
         * @description Все объекты, зарегистрированные в системе.
         */
        get: operations["list_objects_endpoint_api_objects_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/objects/{object_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Карточка объекта
         * @description Объект вместе с камерами и зонами выполнения работ.
         */
        get: operations["get_object_endpoint_api_objects__object_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/objects/{object_id}/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Текущее состояние площадки
         * @description Последний кадр по каждой камере объекта: детекции, зоны, состояние техники.
         */
        get: operations["get_live_endpoint_api_objects__object_id__live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/objects/{object_id}/gantt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * План vs факт по работам
         * @description Диаграмма Ганта: плановые и фактические машино-часы, прогноз завершения, SPI.
         */
        get: operations["get_gantt_endpoint_api_objects__object_id__gantt_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/objects/{object_id}/economics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Экономика: КИТ, простои, рубли
         * @description Коэффициент использования техники и стоимость простоя за период.
         */
        get: operations["get_economics_endpoint_api_objects__object_id__economics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/objects/{object_id}/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Импорт графика (XLSX / MS Project XML)
         * @description Заменяет график объекта данными из загруженного файла — нечёткое сопоставление колонок, см. `services/analytics/schedule_io.py`.
         */
        post: operations["import_schedule_endpoint_api_objects__object_id__schedule_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/objects/{object_id}/deviations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Лента отклонений
         * @description Отклонения по объекту, опционально отфильтрованные по типу (R0-R4).
         */
        get: operations["list_deviations_endpoint_api_objects__object_id__deviations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/deviations/{deviation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Карточка отклонения с доказательствами
         * @description Числа плана и факта, формулировка на русском, рекомендация, кадры-улики.
         */
        get: operations["get_deviation_endpoint_api_deviations__deviation_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/deviations/{deviation_id}/act": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Сформировать PDF-акт
         * @description Формирует PDF-акт по отклонению для передачи подрядчику; отклонение помечается как `acted`.
         */
        post: operations["create_act_endpoint_api_deviations__deviation_id__act_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cameras/{camera_id}/zones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Сохранить полигоны зон
         * @description Полная замена разметки зон выполнения работ для камеры.
         */
        post: operations["update_zones_endpoint_api_cameras__camera_id__zones_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/objects/{object_id}/replay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Машина времени: проигрывание предрассчитанного периода
         * @description Server-Sent Events: кадры с детекциями объекта за период `from`-`to`, воспроизведённые с ускорением `speed` (во сколько раз быстрее реального времени; по умолчанию — `HG_REPLAY_SPEED`). Каждое событие `frame` — один кадр по контракту `detections.jsonl`; в конце — событие `end`.
         */
        get: operations["replay_endpoint_api_objects__object_id__replay_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Проверка живости сервиса */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_import_schedule_endpoint_api_objects__object_id__schedule_post */
        Body_import_schedule_endpoint_api_objects__object_id__schedule_post: {
            /** File */
            file: string;
        };
        /** CameraOut */
        CameraOut: {
            /**
             * Camera Id
             * @description Идентификатор камеры
             */
            camera_id: string;
            /**
             * Title
             * @description Название ракурса
             * @default
             */
            title: string;
            /**
             * Source Kind
             * @description Тип источника: rtsp | hls | folder | replay
             */
            source_kind: string;
            /**
             * Source Uri
             * @description Адрес источника кадров
             */
            source_uri: string;
            /**
             * Capture Interval Sec
             * @description Номинальный интервал съёмки, сек
             */
            capture_interval_sec: number;
            /**
             * Zones
             * @description Зоны выполнения работ этой камеры
             */
            zones?: components["schemas"]["ZoneOut"][];
        };
        /** DetectedObjectOut */
        DetectedObjectOut: {
            /**
             * Track Id
             * @description Стабильный идентификатор трека
             */
            track_id: number;
            /**
             * Cls
             * @description Класс техники
             */
            cls: string;
            /**
             * Conf
             * @description Уверенность детектора, 0..1
             */
            conf: number;
            /**
             * Bbox
             * @description Бокс [x, y, ширина, высота] в пикселях кадра
             */
            bbox: number[];
            /**
             * Zone Id
             * @description Зона, в которой находится техника
             */
            zone_id?: string | null;
            /**
             * State
             * @description Состояние: active | idle | parked | unknown
             */
            state: string;
            /**
             * State Conf
             * @description Уверенность классификатора состояния, 0..1
             */
            state_conf: number;
            features: components["schemas"]["FeaturesOut"];
        };
        /** DetectionFrameOut */
        DetectionFrameOut: {
            /**
             * Camera Id
             * @description Камера, снявшая кадр
             */
            camera_id: string;
            /**
             * Ts
             * @description Время кадра, ISO 8601, +03:00
             */
            ts: string;
            /**
             * Frame Uri
             * @description Путь к файлу кадра
             */
            frame_uri: string;
            quality: components["schemas"]["QualityOut"];
            /** Objects */
            objects?: components["schemas"]["DetectedObjectOut"][];
        };
        /** DeviationOut */
        DeviationOut: {
            /**
             * Deviation Id
             * @description Идентификатор отклонения
             */
            deviation_id: string;
            /**
             * Detected At
             * @description Когда отклонение обнаружено, ISO 8601
             */
            detected_at: string;
            period: components["schemas"]["PeriodOut"];
            /**
             * Work Id
             * @description Работа графика, к которой относится отклонение
             */
            work_id?: string | null;
            /**
             * Zone Id
             * @description Зона, в которой обнаружено отклонение
             */
            zone_id: string;
            /**
             * Type
             * @description Тип: R0_low_confidence | R1_resource_gap | R2_idle | R3_front_mismatch | R4_silence
             */
            type: string;
            /**
             * Severity
             * @description Серьёзность: low | medium | high
             */
            severity: string;
            /**
             * Observed
             * @description Факт (числа плана/факта по контексту типа)
             */
            observed?: {
                [key: string]: unknown;
            };
            /**
             * Expected
             * @description План/ожидание по контексту типа
             */
            expected?: {
                [key: string]: unknown;
            };
            impact: components["schemas"]["ImpactOut"];
            /**
             * Explanation
             * @description Формулировка на русском для прораба
             */
            explanation: string;
            /**
             * Recommendation
             * @description Рекомендация на русском
             */
            recommendation: string;
            evidence: components["schemas"]["EvidenceOut"];
            /**
             * Status
             * @description open — новое, acted — по нему сформирован акт
             * @default open
             */
            status: string;
        };
        /** EconomicsOut */
        EconomicsOut: {
            /** Object Id */
            object_id: string;
            /**
             * Period
             * @description Запрошенный период {from, to}
             */
            period: {
                [key: string]: string;
            };
            /**
             * Currency
             * @default RUB
             */
            currency: string;
            /**
             * Total Idle Cost Rub
             * @description Суммарные потери от простоя за период, ₽
             */
            total_idle_cost_rub: number;
            /** By Class */
            by_class: components["schemas"]["UtilizationRowOut"][];
        };
        /** EvidenceOut */
        EvidenceOut: {
            /**
             * Frames
             * @description Кадры-улики
             */
            frames?: string[];
            /**
             * Chart
             * @description Какой график показать в карточке
             * @default mh_plan_vs_fact
             */
            chart: string;
            /**
             * Confidence
             * @description Уверенность системы в отклонении, 0..1
             */
            confidence: number;
        };
        /** FeaturesOut */
        FeaturesOut: {
            /**
             * Centroid Mad
             * @description MAD смещения центра нижней грани бокса за окно
             */
            centroid_mad: number;
            /**
             * Area Mad
             * @description MAD площади бокса за окно
             */
            area_mad: number;
            /**
             * Flow Mag
             * @description Средняя величина оптического потока внутри бокса
             */
            flow_mag: number;
            /**
             * Hsv Var
             * @description Пространственная дисперсия HSV внутри бокса
             */
            hsv_var: number;
        };
        /** GanttOut */
        GanttOut: {
            /** Object Id */
            object_id: string;
            /**
             * Period
             * @description Запрошенный период {from, to}
             */
            period: {
                [key: string]: string;
            };
            /** Works */
            works: components["schemas"]["WorkProgressOut"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImpactOut */
        ImpactOut: {
            /**
             * Spi
             * @description Индекс выполнения по срокам на момент детекции
             */
            spi?: number | null;
            /**
             * Delay Days
             * @description Прогнозное отставание, суток
             */
            delay_days?: number | null;
            /**
             * Idle Cost Rub
             * @description Стоимость простоя за период, ₽
             * @default 0
             */
            idle_cost_rub: number;
        };
        /** LiveStateOut */
        LiveStateOut: {
            /**
             * Object Id
             * @description Идентификатор объекта
             */
            object_id: string;
            /**
             * Ts
             * @description Время формирования ответа, ISO 8601
             */
            ts: string;
            /**
             * Cameras
             * @description Последний известный кадр по каждой камере объекта
             */
            cameras?: components["schemas"]["DetectionFrameOut"][];
        };
        /** ObjectDetailOut */
        ObjectDetailOut: {
            /**
             * Object Id
             * @description Идентификатор объекта строительства
             */
            object_id: string;
            /**
             * Name
             * @description Название объекта
             */
            name: string;
            /**
             * Address
             * @description Адрес объекта
             * @default
             */
            address: string;
            /**
             * Timezone
             * @description Часовой пояс объекта
             * @default Europe/Moscow
             */
            timezone: string;
            /**
             * Cameras
             * @description Камеры объекта
             */
            cameras?: components["schemas"]["CameraOut"][];
        };
        /** ObjectOut */
        ObjectOut: {
            /**
             * Object Id
             * @description Идентификатор объекта строительства
             */
            object_id: string;
            /**
             * Name
             * @description Название объекта
             */
            name: string;
            /**
             * Address
             * @description Адрес объекта
             * @default
             */
            address: string;
            /**
             * Timezone
             * @description Часовой пояс объекта
             * @default Europe/Moscow
             */
            timezone: string;
        };
        /** PeriodOut */
        PeriodOut: {
            /**
             * From
             * @description Начало периода отклонения
             */
            from: string;
            /**
             * To
             * @description Конец периода отклонения
             */
            to: string;
        };
        /** QualityOut */
        QualityOut: {
            /**
             * Blur
             * @description Размытость кадра, 0 — резкий, 1 — сильно размыт
             */
            blur: number;
            /**
             * Night
             * @description Признак ночного кадра
             */
            night: boolean;
            /**
             * Occlusion
             * @description Доля кадра, закрытая помехой (грязный объектив и т.п.)
             */
            occlusion: number;
            /**
             * Score
             * @description Итоговая оценка качества кадра, 0..1
             */
            score: number;
        };
        /** ScheduleImportResult */
        ScheduleImportResult: {
            /**
             * Object Id
             * @description Объект, для которого импортирован график
             */
            object_id: string;
            /**
             * Imported Count
             * @description Число импортированных работ
             */
            imported_count: number;
            /**
             * Works
             * @description Импортированные работы
             */
            works: components["schemas"]["ScheduleWorkOut"][];
        };
        /** ScheduleWorkOut */
        ScheduleWorkOut: {
            /**
             * Work Id
             * @description Идентификатор работы
             */
            work_id: string;
            /**
             * Wbs
             * @description Номер в иерархии графика (WBS)
             * @default
             */
            wbs: string;
            /**
             * Name
             * @description Наименование работы
             */
            name: string;
            /**
             * Work Type
             * @description Вид работ (ресурсный отпечаток)
             */
            work_type?: string | null;
            /**
             * Zone Id
             * @description Зона выполнения
             */
            zone_id?: string | null;
            /**
             * Start Plan
             * @description Плановая дата начала
             */
            start_plan: string;
            /**
             * Finish Plan
             * @description Плановая дата окончания
             */
            finish_plan: string;
            volume: components["schemas"]["VolumeOut"];
            /**
             * Planned Mh
             * @description Плановые машино-часы по классам техники
             */
            planned_mh?: {
                [key: string]: number;
            };
            /**
             * Predecessors
             * @description Работы-предшественники
             */
            predecessors?: string[];
        };
        /** UtilizationRowOut */
        UtilizationRowOut: {
            /** Zone Id */
            zone_id: string;
            /**
             * Cls
             * @description Класс техники
             */
            cls: string;
            /**
             * Mh Present
             * @description Часы присутствия на площадке
             */
            mh_present: number;
            /**
             * Mh Active
             * @description Часы фактической работы
             */
            mh_active: number;
            /**
             * Mh Idle
             * @description Часы простоя
             */
            mh_idle: number;
            /**
             * Utilization
             * @description КИТ = mh_active / mh_present
             */
            utilization: number;
            /**
             * Idle Cost Rub
             * @description Стоимость простоя, ₽
             */
            idle_cost_rub: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VolumeOut */
        VolumeOut: {
            /**
             * Unit
             * @description Единица измерения объёма работ
             */
            unit?: string | null;
            /**
             * Qty
             * @description Объём работ в этой единице
             */
            qty?: number | null;
        };
        /** WorkProgressOut */
        WorkProgressOut: {
            /**
             * Date
             * @description Дата, на которую посчитан прогресс
             */
            date: string;
            /**
             * Work Id
             * @description Идентификатор работы
             */
            work_id: string;
            /**
             * Name
             * @description Наименование работы
             */
            name: string;
            /**
             * Mh Plan To Date
             * @description План машино-часов нарастающим итогом
             */
            mh_plan_to_date: number;
            /**
             * Mh Fact To Date
             * @description Факт машино-часов нарастающим итогом
             */
            mh_fact_to_date: number;
            /**
             * Spi
             * @description Индекс выполнения по срокам = факт / план
             */
            spi: number;
            /**
             * Rate Mh Per Day
             * @description Текущий темп, маш.-ч/сут
             */
            rate_mh_per_day: number;
            /**
             * Forecast Finish
             * @description Прогнозная дата завершения
             */
            forecast_finish?: string | null;
            /**
             * Delay Days
             * @description Прогнозное отставание, суток
             */
            delay_days?: number | null;
            /**
             * Status
             * @description Светофор: green | yellow | red
             */
            status: string;
        };
        /** ZoneIn */
        ZoneIn: {
            /**
             * Zone Id
             * @description Идентификатор зоны
             */
            zone_id: string;
            /**
             * Title
             * @description Название зоны
             * @default
             */
            title: string;
            /**
             * Polygon
             * @description Полигон зоны на кадре, [[x,y], ...]
             */
            polygon: number[][];
            /**
             * Area M2
             * @description Площадь зоны, м²
             */
            area_m2?: number | null;
        };
        /** ZoneOut */
        ZoneOut: {
            /**
             * Zone Id
             * @description Идентификатор зоны выполнения работ
             */
            zone_id: string;
            /**
             * Title
             * @description Человекочитаемое название зоны
             * @default
             */
            title: string;
            /**
             * Polygon
             * @description Полигон зоны на кадре, [[x,y], ...]
             */
            polygon: number[][];
            /**
             * Area M2
             * @description Площадь зоны, м²
             */
            area_m2?: number | null;
        };
        /** ZonesUpdateResult */
        ZonesUpdateResult: {
            /** Camera Id */
            camera_id: string;
            /** Zones */
            zones: components["schemas"]["ZoneOut"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_objects_endpoint_api_objects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObjectOut"][];
                };
            };
        };
    };
    get_object_endpoint_api_objects__object_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                object_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObjectDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_live_endpoint_api_objects__object_id__live_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                object_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiveStateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_gantt_endpoint_api_objects__object_id__gantt_get: {
        parameters: {
            query: {
                /** @description Начало периода */
                from: string;
                /** @description Конец периода (на эту дату считается прогресс) */
                to: string;
            };
            header?: never;
            path: {
                object_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GanttOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_economics_endpoint_api_objects__object_id__economics_get: {
        parameters: {
            query: {
                /** @description Начало периода */
                from: string;
                /** @description Конец периода */
                to: string;
            };
            header?: never;
            path: {
                object_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EconomicsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_schedule_endpoint_api_objects__object_id__schedule_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                object_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_schedule_endpoint_api_objects__object_id__schedule_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleImportResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_deviations_endpoint_api_objects__object_id__deviations_get: {
        parameters: {
            query?: {
                /** @description Фильтр по типу отклонения */
                type?: string | null;
            };
            header?: never;
            path: {
                object_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviationOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_deviation_endpoint_api_deviations__deviation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deviation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_act_endpoint_api_deviations__deviation_id__act_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deviation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "application/pdf": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_zones_endpoint_api_cameras__camera_id__zones_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                camera_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ZoneIn"][];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ZonesUpdateResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    replay_endpoint_api_objects__object_id__replay_get: {
        parameters: {
            query?: {
                /** @description Ускорение воспроизведения */
                speed?: number | null;
                /** @description Начало периода */
                from?: string | null;
                /** @description Конец периода */
                to?: string | null;
            };
            header?: never;
            path: {
                object_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
